### ISSUE TITLE
Epoch Amp: sound panned right

### ISSUE THREAD

**Issue by buscon** [GuitarML/Releases#1]
I am using Epoch Amp 1.0 on Windows 11.

when I use the VST the sound is slightly (about 15%) panned to the right channel.
My source is mono and it does stay mono when I turn off the Epoch Amp, it is panned to the right channel as soon as I turn it on, independently from which setting I choose in the Epoch Amp.

**Comment by GuitarML** [comment]
@buscon Thank you for reporting this issue. That seems odd, what DAW and audio device (ASIO or something different) are you using? If you re-load the VST3 or reset the DAW does the panning go away? If it was a stereo vs. mono issue I would expect it to be panned 100% one way, so possibly something to do with the clean/dirty mix. If you adjust the mix control, can you tell if it only mixes one side (left/right)?

**Comment by buscon** [comment]
@GuitarML sorry for the late answer. I ended up realizing it was a problem with my DAW, sorry about about the wrong claim and thanks for your answer.
